#!/bin/bash -eu


## Удаление старых бекапов из DataStorage
##
## Параметры:
#~ Login    Имя пользователя услуги DataStorage
#~ Days     Кол-во дней хранения бекапов


print_usage() {
    cat >&2 <<EOF
Usage:

    ${0##*/} LOGIN(DataStorage) DAYS

EOF
    exit 2
}


(( $# == 2 )) || {
    print_usage
}


declare -r LOGIN="$1"
declare -r DAYS="$2"

declare -r PRIV_KEY='/root/.ssh/id_rsa_ds'
declare -r REMOTE_SERVER="sftp -i ${PRIV_KEY} ${LOGIN}@storage.${LOGIN}.netangels.ru:"
declare -r BACKUP_DIR="/${LOGIN}/backup"

declare -r MAX_DATE="$(date +%Y%m%d -d "-$DAYS days")"
declare -r TEMP_DIR="$(mktemp -d /tmp/DS.d.XXXXXXXX)"
trap "rm -rf $TEMP_DIR" 0


# Проверка, что есть несколько full-бекапов

[[ "$(echo "ls -1 $BACKUP_DIR" | $REMOTE_SERVER 2>/dev/null | grep 'full.tar.lzo.split_aa' | wc -l)" -ne 1 ]] || {
    echo 'Warning: last full-backup'
    exit 0
}


echo "ls -1 $BACKUP_DIR" | $REMOTE_SERVER 2>/dev/null | sed -e 's/[a-zA-Z0-9\/]*-//' -e 's/-[a-zA-Z0-9\/\.\_]*//' | awk "{ if (\$0 <= $MAX_DATE) print \$1 }" | uniq -c | awk '{print $2}' > "${TEMP_DIR}/date"

touch ${TEMP_DIR}/files
for DATE in $(cat ${TEMP_DIR}/date); do
    echo "ls -1 $BACKUP_DIR" | $REMOTE_SERVER 2>/dev/null | grep "$DATE" >> ${TEMP_DIR}/files
done


declare -ri COUNT="$(cat ${TEMP_DIR}/files | wc -l)"


[[ "$COUNT" -gt 0 ]] && {
    [[ "$(grep -c '.full.tar.lzo.split_.*$' "${TEMP_DIR}/files")" -gt 1 ]] || exit 10

    for FILE in $(cat ${TEMP_DIR}/files); do
        echo "rm $FILE" | $REMOTE_SERVER 1>/dev/null 2>&1
    done
} || :
